gen_uuid.c: s/_SVID_SOURCE/_DEFAULT_SOURCE/
With the latest glibc, I get this warning:

gcc -c <snip/>  -o ../../../z-Build/Debug/.obj/PrlUuid/gen_uuid.o libuuid_unix/gen_uuid.c
In file included from /usr/include/unistd.h:25:0,
                 from libuuid_unix/gen_uuid.c:42:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
cc1: all warnings being treated as errors
Makefile.Debug:214: recipe for target '../../../z-Build/Debug/.obj/PrlUuid/gen_uuid.o' failed

The problem is originating in features.h:

  #if (defined _BSD_SOURCE || defined _SVID_SOURCE) \
      && !defined _DEFAULT_SOURCE
  # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
  # undef  _DEFAULT_SOURCE
  # define _DEFAULT_SOURCE	1
  #endif

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>